mielqnh/bazinga3

- src/main/java/be/mielnoelanders/bazinga/repository/GameRepository.java
- src/main/java/be/mielnoelanders/bazinga/service/GameService.java
- src/main/java/be/mielnoelanders/bazinga/service/GameServiceImpl.java
Dit is een test, maar wel voor echt
> Gamerepository klaar

- src/main/java/be/mielnoelanders/bazinga/service/CustomerService.java
- src/main/java/be/mielnoelanders/bazinga/service/CustomerServiceImpl.java
> customerservice klaar

- src/main/java/be/mielnoelanders/bazinga/restcontroller/CustomerEndPoint.java
> cep klasse gemaakt

- src/main/java/be/mielnoelanders/bazinga/repository/PublisherRepository.java
- src/main/java/be/mielnoelanders/bazinga/service/PublisherService.java
- src/main/java/be/mielnoelanders/bazinga/service/PublisherServiceImpl.java
> PublisherServiceTest updated

- src/main/java/be/mielnoelanders/bazinga/restcontroller/CustomerEndPoint.java
Mk restcontroller met standaard crud-methods
> Mk restcontroller

- src/main/java/be/mielnoelanders/bazinga/restcontroller/ParameterEndPoint.java
> PublisherEndPoint created

- src/main/java/be/mielnoelanders/bazinga/domain/Parameter.java
- src/main/java/be/mielnoelanders/bazinga/repository/ParameterRepository.java
- src/main/java/be/mielnoelanders/bazinga/restcontroller/ParameterEndPoint.java
- src/main/java/be/mielnoelanders/bazinga/service/ParameterService.java
- src/main/java/be/mielnoelanders/bazinga/service/ParameterServiceImpl.java
> PublisherEndPoint updated

- src/main/java/be/mielnoelanders/bazinga/domain/AbstractEntity.java
- src/main/java/be/mielnoelanders/bazinga/repository/GameRepository.java
- src/main/java/be/mielnoelanders/bazinga/restcontroller/GameEndPoint.java
- src/main/java/be/mielnoelanders/bazinga/service/GameService.java
- src/main/java/be/mielnoelanders/bazinga/service/GameServiceImpl.java
- src/test/java/be/mielnoelanders/bazinga/service/GameServiceUnitTest.java
> Mn game test met mockito

- src/main/java/be/mielnoelanders/bazinga/service/SupplierServiceImpl.java
.orElse om geen "IllegalArgumentException - if id is null" te krijgen
> SupplierServiceImpl method findById aangepast

- pom.xml
- src/main/java/be/mielnoelanders/bazinga/restcontroller/SupplierEndPoint.java
- src/test/java/be/mielnoelanders/bazinga/service/GameServiceUnitTest.java
- src/test/java/be/mielnoelanders/bazinga/service/SupplierServiceUnitTest.java
> SupplierServiceUnitTest : method testFindById

- src/main/java/be/mielnoelanders/bazinga/service/GameServiceImpl.java
- src/test/java/be/mielnoelanders/bazinga/service/GameServiceIntegrationTest.java
- src/test/java/be/mielnoelanders/bazinga/service/GameServiceUnitTest.java
Beetje zaterdagavondwerk never hurt anyone!
> Integratietest gameservice WERKT

- src/test/java/be/mielnoelanders/bazinga/service/SupplierServiceUnitTest.java
> Mk supplier service test

- src/test/java/be/mielnoelanders/bazinga/restcontroller/SupplierEndPointIntegrationTestIT.java
- src/test/resources/application.properties
> SupplierEndPointIntegrationTest : method testAddOne

- src/test/java/be/mielnoelanders/bazinga/restcontroller/SupplierEndPointIntegrationTestIT.java
> SupplierEndPointIntegrationTest : method testFindById

- src/main/java/be/mielnoelanders/bazinga/restcontroller/PublisherEndPoint.java
> WmPublisherEndPoint added

- src/main/java/be/mielnoelanders/bazinga/restcontroller/ParameterEndPoint.java
- src/main/java/be/mielnoelanders/bazinga/restcontroller/PublisherEndPoint.java
- src/main/java/be/mielnoelanders/bazinga/service/PublisherServiceImpl.java
- src/test/java/be/mielnoelanders/bazinga/service/PublisherServiceIT.java
> Wm publisher it

- src/test/java/be/mielnoelanders/bazinga/restcontroller/SupplierEndPointIntegrationTestIT.java
> SupplierEndPointIntegrationTest : method testDeleteById

- src/test/java/be/mielnoelanders/bazinga/restcontroller/SupplierEndPointIntegrationTestIT.java
method testCreateFindAllReadUpdateDelete()
> SupplierEndPointIntegrationTest

- src/main/java/be/mielnoelanders/bazinga/restcontroller/CustomerEndPoint.java
- src/test/java/be/mielnoelanders/bazinga/restcontroller/CustomerEndPointIT.java
method testCreateFindAllReadUpdateDelete()
> CustomerEndPointIntegrationTest 

- src/main/java/be/mielnoelanders/bazinga/restcontroller/CustomerEndPoint.java
- src/main/java/be/mielnoelanders/bazinga/restcontroller/SupplierEndPoint.java
- src/main/java/be/mielnoelanders/bazinga/service/CustomerService.java
- src/main/java/be/mielnoelanders/bazinga/service/CustomerServiceImpl.java
- src/main/java/be/mielnoelanders/bazinga/service/SupplierService.java
- src/main/java/be/mielnoelanders/bazinga/service/SupplierServiceImpl.java
- src/test/java/be/mielnoelanders/bazinga/service/CustomerServiceIntegrationTestIT.java
- src/test/java/be/mielnoelanders/bazinga/service/CustomerServiceUnitTest.java
- src/test/java/be/mielnoelanders/bazinga/service/SupplierServiceIntegrationTestIT.java
- src/test/java/be/mielnoelanders/bazinga/service/SupplierServiceUnitTest.java
method names gestandaardiseert
> Mk update service method names

- src/main/java/be/mielnoelanders/bazinga/restcontroller/SupplierEndPoint.java
updated requestmapping from "/getall" to "/findall"
> SupplierEndPoint 
